services:
  staging_b2b_tickets_pre_entry_1:
    build:
      context: .
      dockerfile: apps/b2b_tickets/Dockerfile
    image: b2b_tickets_img_preentry:${STAGING_B2B_VERSION_TEST:-1.0.7}
    ports:
      - '5001:3000'
    container_name: Staging_B2B_Tickets_PreEntry_1
    extra_hosts:
      - 'emailrelay:10.0.1.19'
      - 'sms-gw1:10.131.12.77'
      - 'sms-gw2:10.131.20.78'
      - 'test-sms-gw1:10.131.28.73'
      - 'b2b_database:172.27.52.177'
    environment:
      - NODE_ENV=production
      - APP_ENV=staging
      - PORT=3000
    command: >
      sh -c "cp /app/env-files/.env.staging /app/apps/b2b_tickets/.env.production &&
             cp /app/env-files/staging.ts /app/libs/config/src/lib/production.ts &&
             nx start b2b_tickets --verbose"
    volumes:
      - /var/log/b2b_test:/app/apps/b2b_tickets/logs/development
      - /home/centos/Staging_Environment_Variables/.env.staging:/app/env-files/.env.staging
      - /home/centos/Staging_Configuration/staging.ts:/app/env-files/staging.ts
    restart: unless-stopped

  staging_b2b_tickets_pre_entry_2:
    build:
      context: .
      dockerfile: apps/b2b_tickets/Dockerfile
    image: b2b_tickets_img_preentry:${STAGING_B2B_VERSION_TEST:-1.0.7}
    ports:
      - '5002:3000'
    container_name: Staging_B2B_Tickets_PreEntry_2
    extra_hosts:
      - 'emailrelay:10.0.1.19'
      - 'sms-gw1:10.131.12.77'
      - 'sms-gw2:10.131.20.78'
      - 'test-sms-gw1:10.131.28.73'
      - 'b2b_database:172.27.52.177'
    environment:
      - NODE_ENV=production
      - APP_ENV=staging
      - PORT=3000
    command: >
      sh -c "cp /app/env-files/.env.staging /app/apps/b2b_tickets/.env.production &&
             cp /app/env-files/staging.ts /app/libs/config/src/lib/production.ts &&
             nx start b2b_tickets --verbose"
    volumes:
      - /var/log/b2b_test:/app/apps/b2b_tickets/logs/development
      - /home/centos/Staging_Environment_Variables/.env.staging:/app/env-files/.env.staging
      - /home/centos/Staging_Configuration/staging.ts:/app/env-files/staging.ts
    restart: unless-stopped

  prod_b2b_tickets_1:
    build:
      context: .
      dockerfile: apps/b2b_tickets/Dockerfile
    image: b2b_tickets_img_production:${PROD_B2B_VERSION:-1.0.5}
    ports:
      - '8001:3000'
    container_name: Prod_B2B_Tickets_1
    extra_hosts:
      - 'emailrelay:10.0.1.19'
      - 'sms-gw1:10.131.12.77'
      - 'sms-gw2:10.131.20.78'
      - 'test-sms-gw1:10.131.28.73'
      - 'b2b_database:172.27.52.177'
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: ['nx', 'start', 'b2b_tickets', '--verbose']
    volumes:
      - /var/log/b2b_prod:/app/apps/b2b_tickets/logs/production
    restart: unless-stopped

  prod_b2b_tickets_2:
    build:
      context: .
      dockerfile: apps/b2b_tickets/Dockerfile
    image: b2b_tickets_img_production:${PROD_B2B_VERSION:-1.0.5}
    ports:
      - '8002:3000'
    container_name: Prod_B2B_Tickets_2
    extra_hosts:
      - 'emailrelay:10.0.1.19'
      - 'sms-gw1:10.131.12.77'
      - 'sms-gw2:10.131.20.78'
      - 'test-sms-gw1:10.131.28.73'
      - 'b2b_database:172.27.52.177'
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: ['nx', 'start', 'b2b_tickets', '--verbose']
    volumes:
      - /var/log/b2b_prod:/app/apps/b2b_tickets/logs/production
    restart: unless-stopped

  staging_socket_server_pre_entry_1:
    build:
      context: .
      dockerfile: apps/socket-server/Dockerfile
    image: staging_socket_server_img_preentry:${STAGING_B2B_VERSION_TEST:-1.0.5}
    ports:
      - '3456:3456'
    container_name: Staging_Socket_Server_PreEntry_1
    extra_hosts:
      - 'emailrelay:10.0.1.19'
      - 'sms-gw1:10.131.12.77'
      - 'sms-gw2:10.131.20.78'
      - 'test-sms-gw1:10.131.28.73'
      - 'b2b_database:172.27.52.177'
    environment:
      - NODE_ENV=staging
      - DEBUG=1
      - PORT=3456
      - SOCKET_CORS_ORIGIN=https://10.124.49.151:8444
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NEXT_AUTH_SESSION_URL=https://10.124.49.151:8444/api/auth/session
    command: >
      sh -c "nx build socket-server --configuration=staging --verbose &&
             node dist/apps/socket-server/main.js"
    restart: unless-stopped

  production_socket_server_1:
    build:
      context: .
      dockerfile: apps/socket-server/Dockerfile
    image: production_socket_server_img:${STAGING_B2B_VERSION_TEST:-1.0.5}
    ports:
      - '3457:3457'
    container_name: Production_Socket_Server_1
    extra_hosts:
      - 'emailrelay:10.0.1.19'
      - 'sms-gw1:10.131.12.77'
      - 'sms-gw2:10.131.20.78'
      - 'test-sms-gw1:10.131.28.73'
      - 'b2b_database:172.27.52.177'
    environment:
      - NODE_ENV=staging
      - DEBUG=1
      - PORT=3457
      - SOCKET_CORS_ORIGIN=https://10.124.49.151
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NEXT_AUTH_SESSION_URL=https://10.124.49.151/api/auth/session
    command: >
      sh -c "nx build socket-server --configuration=staging --verbose &&
             node dist/apps/socket-server/main.js"
    restart: unless-stopped
