services:
  staging_b2b_tickets_pre_entry_1:
    build:
      context: .
      dockerfile: apps/b2b_tickets/Dockerfile
    image: b2b_tickets_img_preentry:${STAGING_B2B_VERSION_TEST:-1.0.2}
    ports:
      - '${B2B_TICKETS_PORT_1:-5001}:3000'
    container_name: Staging_B2B_Tickets_PreEntry_1
    dns:
      - ${DNS_SERVER:-1.1.1.1}
    extra_hosts:
      - 'emailrelay:${EMAIL_RELAY_IP}'
      - 'sms-gw1:${SMS_GW1_IP}'
      - 'sms-gw2:${SMS_GW2_IP}'
      - 'test-sms-gw1:${TEST_SMS_GW1_IP}'
      - 'b2b_database:${B2B_DATABASE_IP}'
      - 'redis_host:127.0.0.1'
    environment:
      - NODE_ENV=production
      - APP_ENV=staging
      - PORT=3000
    command: >
      sh -c "cp /app/env-files/.env.staging_macOnly /app/apps/b2b_tickets/.env.production &&
             cp /app/env-files/.env_staging_config_macOnly /app/libs/config/src/lib/production.ts &&
             nx start b2b_tickets --verbose"
    volumes:
      - /Users/apostoloskapetanios/LocalProgramming/b2b_tickets/apps/b2b_tickets/.env.staging_macOnly:/app/env-files/.env.staging_macOnly
      - /Users/apostoloskapetanios/LocalProgramming/b2b_tickets/apps/b2b_tickets/.env_staging_config_macOnly:/app/env-files/.env_staging_config_macOnly
    restart: unless-stopped
