version: "3.8"

services:
  b2b_ticketing_test:
    build:
      context: .
      dockerfile: apps/b2b_tickets
    image: nms_portal_image:${NMS_PORTAL_VERSION:-1.0.1}
    ports:
      - "7001:7001"
    container_name: NMS_Portal_Container_1
    extra_hosts:
      - "pirdc01.sys.telestet.gr:10.66.1.11"
    environment:
      - NODE_ENV=production
      - PORT=7001
    command: ["nx", "start", "NMS_Portal"]
    depends_on:
      - my_nx_monorepo_base
    volumes:
      - /var/log/NMS_Portal:/app/apps/NMS_Portal/logs/production