services:
  staging_b2b_tickets_pre_entry_1:
    build:
      context: .
      dockerfile: apps/b2b_tickets/Dockerfile
    image: b2b_tickets_img_preentry:${STAGING_B2B_VERSION_TEST:-1.0.2}
    ports:
      - '5001:3000'
    container_name: Staging_B2B_Tickets_PreEntry_1
    extra_hosts:
      - 'emailrelay:10.0.1.19'
      - 'sms-gw1:10.131.12.77'
      - 'sms-gw2:10.131.20.78'
      - 'test-sms-gw1:10.131.28.73'
      - 'b2b_database:172.27.52.177'
    environment:
      - NODE_ENV=production
      - APP_ENV=staging
      - PORT=3000
    command: >
      sh -c "cp /app/env-files/.env.staging_macOnly /app/apps/b2b_tickets/.env.production &&
             cp /app/env-files/.env_staging_config_macOnly /app/libs/config/src/lib/production.ts &&
             nx start b2b_tickets --verbose"
    volumes:
      - /Users/apostoloskapetanios/LocalProgramming/b2b_tickets/apps/b2b_tickets/.env.staging_macOnly:/app/env-files/.env.staging_macOnly
      - /Users/apostoloskapetanios/LocalProgramming/b2b_tickets/apps/b2b_tickets/.env_staging_config_macOnly:/app/env-files/.env_staging_config_macOnly
    restart: unless-stopped
