services:
  staging_b2b_tickets_pre_entry_1:
    build:
      context: .
      dockerfile: apps/b2b_tickets/Dockerfile
    image: b2b_tickets_img_preentry:${STAGING_B2B_VERSION_TEST:-1.0.2}
    ports:
      - "5001:3000"
    container_name: Staging_B2B_Tickets_PreEntry_1
    extra_hosts:
      - "emailrelay:10.0.1.19"
      - "sms-gw1:10.131.12.77"
      - "sms-gw2:10.131.20.78"
      - "test-sms-gw1:10.131.28.73"
      - "b2b_database:172.27.52.177"
    environment:
      - NODE_ENV=production
      - APP_ENV=staging
      - PORT=3000
    command: >
      sh -c "cp /app/env-files/.env.staging /app/apps/b2b_tickets/.env.production &&
             cp /app/env-files/staging.ts /app/libs/config/src/lib/production.ts &&
             nx start b2b_tickets --verbose"
    volumes:
      - /var/log/b2b_test:/app/apps/b2b_tickets/logs/development
      - /home/centos/Staging_Environment_Variables/.env.staging:/app/env-files/.env.staging
      - /home/centos/Staging_Configuration/staging.ts:/app/env-files/staging.ts
    restart: unless-stopped


  staging_b2b_tickets_pre_entry_2:
    build:
      context: .
      dockerfile: apps/b2b_tickets/Dockerfile
    image: b2b_tickets_img_preentry:${STAGING_B2B_VERSION_TEST:-1.0.2}
    ports:
      - "5002:3000"
    container_name: Staging_B2B_Tickets_PreEntry_2
    extra_hosts:
      - "emailrelay:10.0.1.19"
      - "sms-gw1:10.131.12.77"
      - "sms-gw2:10.131.20.78"
      - "test-sms-gw1:10.131.28.73"
      - "b2b_database:172.27.52.177"
    environment:
      - NODE_ENV=production
      - APP_ENV=staging
      - PORT=3000
    command: >
      sh -c "cp /app/env-files/.env.staging /app/apps/b2b_tickets/.env.production &&
             cp /app/env-files/staging.ts /app/libs/config/src/lib/production.ts &&
             nx start b2b_tickets --verbose"
    volumes:
      - /var/log/b2b_test:/app/apps/b2b_tickets/logs/development
      - /home/centos/Staging_Environment_Variables/.env.staging:/app/env-files/.env.staging
      - /home/centos/Staging_Configuration/staging.ts:/app/env-files/staging.ts
    restart: unless-stopped


  prod_b2b_tickets_1:
    build:
      context: .
      dockerfile: apps/b2b_tickets/Dockerfile
    image: b2b_tickets_img_production:${PROD_B2B_VERSION:-1.0.2}
    ports:
      - "8001:3000"
    container_name: Prod_B2B_Tickets_1
    extra_hosts:
      - "emailrelay:10.0.1.19"
      - "sms-gw1:10.131.12.77"
      - "sms-gw2:10.131.20.78"
      - "test-sms-gw1:10.131.28.73"
      - "b2b_database:172.27.52.177"
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: ["nx", "start", "b2b_tickets", "--verbose"]
    volumes:
      - /var/log/b2b_prod:/app/apps/b2b_tickets/logs/production
    restart: unless-stopped

  prod_b2b_tickets_2:
    build:
      context: .
      dockerfile: apps/b2b_tickets/Dockerfile
    image: b2b_tickets_img_production:${PROD_B2B_VERSION:-1.0.2}
    ports:
      - "8001:3000"
    container_name: Prod_B2B_Tickets_2
    extra_hosts:
      - "emailrelay:10.0.1.19"
      - "sms-gw1:10.131.12.77"
      - "sms-gw2:10.131.20.78"
      - "test-sms-gw1:10.131.28.73"
      - "b2b_database:172.27.52.177"
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: ["nx", "start", "b2b_tickets", "--verbose"]
    volumes:
      - /var/log/b2b_prod:/app/apps/b2b_tickets/logs/production
    restart: unless-stopped